# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#
# commands
# docker build -t philip/ubuntu:18.04 .
# docker build -f Dockerfile_Ubuntu_18.04 . -t philip/ubuntu:18.04
# docker run -it -d --rm --name philip_ubunut_18.04 philip/ubuntu:18.04

# Pull base image.
FROM ubuntu:18.04

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y net-tools iputils-ping build-essential curl git htop man unzip vim wget 
  #rm -rf /var/lib/apt/lists/*

# Add files.
#ADD root/.bashrc /root/.bashrc
#ADD root/.gitconfig /root/.gitconfig
#ADD root/.scripts /root/.scripts

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
